services:
    jellyfin:
        container_name: jellyfin
        devices:
            - /dev/dri:/dev/dri
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Denver
            - UMASK_SET=022
        group_add:
            - '105'
        image: jellyfin/jellyfin
        labels:
            traefik.docker.network: traefik
            traefik.enable: true
            traefik.http.routers.jellyfin.entrypoints: websecure
            traefik.http.routers.jellyfin.rule: Host(`jellyfin.<domain>`)
            traefik.http.routers.jellyfin.service: jellyfin
            traefik.http.services.jellyfin.loadbalancer.server.port: 8096
        logging:
            driver: json-file
            options:
                max-size: 50m
                max-file: "3"
        networks:
            traefik: null
        privileged: true
        ports:
            - 7359:7359/udp
        restart: unless-stopped
        volumes:
            - config:/config
            - cache:/cache
            - media:/media
  
    vue:
        container_name: jellyfin_vue
        image: ghcr.io/jellyfin/jellyfin-vue
        labels:
            traefik.docker.network: traefik
            traefik.enable: true
            traefik.http.routers.jellyfin_vue.entrypoints: websecure
            traefik.http.routers.jellyfin_vue.rule: Host(`jellyvue.<domain>`)
            traefik.http.routers.jellyfin_vue.service: jellyfin_vue
            traefik.http.services.jellyfin_vue.loadbalancer.server.port: 80 
        logging:
            driver: json-file
            options:
                max-size: 50m
                max-file: "3"
        networks:
            traefik: null
        restart: unless-stopped

networks:
    traefik:
        name: traefik
        external: true

volumes:
    config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: <path on disk>

    media:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: <path on disk>

    cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: <path on disk>
